import Foundation
import Shared

/// Configuration loaded from whisper_config.json (generated by setup_whisper.sh)
struct WhisperConfig: Codable {
    let whisperLibPath: String
    let modelPath: String
    let coremlModelPath: String?
    let useCoreml: Bool
    let architecture: String
    let modelSize: String

    enum CodingKeys: String, CodingKey {
        case whisperLibPath = "whisper_lib_path"
        case modelPath = "model_path"
        case coremlModelPath = "coreml_model_path"
        case useCoreml = "use_coreml"
        case architecture
        case modelSize = "model_size"
    }

    // Custom decoding to handle both Bool and Int for use_coreml
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        whisperLibPath = try container.decode(String.self, forKey: .whisperLibPath)
        modelPath = try container.decode(String.self, forKey: .modelPath)
        coremlModelPath = try container.decodeIfPresent(String.self, forKey: .coremlModelPath)
        architecture = try container.decode(String.self, forKey: .architecture)
        modelSize = try container.decode(String.self, forKey: .modelSize)

        // Handle both Bool and Int for use_coreml (setup_whisper.sh generates 0/1)
        if let boolValue = try? container.decode(Bool.self, forKey: .useCoreml) {
            useCoreml = boolValue
        } else if let intValue = try? container.decode(Int.self, forKey: .useCoreml) {
            useCoreml = intValue != 0
        } else {
            useCoreml = false
        }
    }
}

/// Loads whisper.cpp configuration from disk
enum WhisperConfigLoader {

    /// Default config file location (uses AppPaths which respects custom location)
    static var defaultConfigPath: String {
        AppPaths.storageRoot + "/whisper_config.json"
    }

    /// Default model path (fallback if config not found, uses AppPaths)
    static var defaultModelPath: String {
        AppPaths.modelsPath + "/ggml-small.bin"
    }

    /// Load whisper configuration from file
    /// - Parameter configPath: Path to whisper_config.json (defaults to standard location)
    /// - Returns: WhisperConfig if found and valid, nil otherwise
    static func loadConfig(from configPath: String = defaultConfigPath) -> WhisperConfig? {
        let expandedPath = NSString(string: configPath).expandingTildeInPath

        guard let data = try? Data(contentsOf: URL(fileURLWithPath: expandedPath)) else {
            return nil
        }

        return try? JSONDecoder().decode(WhisperConfig.self, from: data)
    }

    /// Get the model path from config or fallback to default
    /// - Returns: Path to the whisper model file
    static func getModelPath() -> String {
        if let config = loadConfig() {
            return config.modelPath
        }
        return defaultModelPath
    }

    /// Get CoreML model path if available
    /// - Returns: Path to CoreML model if enabled, nil otherwise
    static func getCoreMLModelPath() -> String? {
        guard let config = loadConfig(), config.useCoreml else {
            return nil
        }
        return config.coremlModelPath
    }

    /// Check if CoreML is enabled
    static func isCoreMLEnabled() -> Bool {
        loadConfig()?.useCoreml ?? false
    }
}
